### ISSUE TITLE
Error Ionic2 run android device

### ISSUE THREAD

**Issue by pegaltier** [VadimDez/ng2-img-fallback#10]
The component work well when i developp using ionic2 on the computer (ionic serve) but it doesn't work when i run the ionic2 app on android phone (ionic run android)

Stacktrace:

[20:10:22]  lint finished in 3.89 s
[20:10:22]  Error: Unexpected value 'Ng2ImgFallback' declared by the module 'AppModule'
[20:10:22]  ngc failed
[20:10:22]  ionic-app-script task: "build"
[20:10:22]  Error: Error

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pegal\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\WorkspaceIntellij\angular-ionic\cutePuppyPics\npm-debug.log
Caught exception:
 undefined

**Comment by fmendoza** [comment]
Is there any workaround for this problem?

**Comment by fmendoza** [comment]
Still not working on Ionic 2 RC3. I'm receiving this error when I run ionic build android:

`Module ''*'' has no exported member 'Wrapper_Ng2ImgFallbackDirective`

**Comment by VadimDez** [comment]
Thanks for feedback. Works for me, take a look here https://github.com/VadimDez/ng2-img-fallback/tree/master/examples/ionic

**Comment by VadimDez** [comment]
@fmendoza, Thanks for feedback!

**Comment by fmendoza** [comment]
Latest commit is working. Android build is generated correctly but typescript is reporting an error in the code. See attachment:

<img width="733" alt="captura de pantalla 2016-11-28 a la s 13 37 57" src="https://cloud.githubusercontent.com/assets/1320696/20683002/fb0a9d18-b56f-11e6-8657-d049c9a037f8.png">

**Comment by VadimDez** [comment]
@fmendoza Can't reproduce it. Try delete folder under `node_modules` and reinstall.

**Comment by fmendoza** [comment]
I just tried but no luck. Let me know if I can help with the code or something to fix it.

Thank you so much

**Comment by fmendoza** [comment]
The error is gone. Maybe it was a cache issue.

**Comment by pegaltier** [comment]
It work, thanks @VadimDez
