### ISSUE TITLE
angular4

### ISSUE THREAD

**Issue by wodka** [VadimDez/ng2-img-fallback#14]
any plans to support angular4?

**Comment by VadimDez** [comment]
Sure!

**Comment by VadimDez** [comment]
Do you get any errors ?
Or just warning ?
```
npm WARN ng2-img-fallback@0.2.2 requires a peer of @angular/core@^2.0.1 but none was installed.
```

**Comment by wodka** [comment]
Just the warning (trying to upgrade an ionic2 project to ionic3).
-> I could not test it because of other dependencies.
