### ISSUE TITLE
Directive is not fired

### ISSUE THREAD

**Issue by chsakell** [VadimDez/ng2-img-fallback#22]
@VadimDez  I tried to use the _src-fallback_ directive but it doesn't work.  Here is how I used it:
```html
<div  *ngFor="let product of products; let i = index">
    <a [routerLink]="['/products/details', product.id]">
          <img class="img-responsive" [src]="product.image" src-fallback="product.cdnImage" alt="" (loaded)="onLoaded($event)">
     </a>
</div>
```
**product.imag**e: A failed image URL (doesn't exist).
**product.cdnImage**: A valid image URL.

Also when using [src-fallback] I get **[Angular] Can't bind to 'src-fallback' since it isn't a known property of 'img'**. 

The onLoaded event doesn't event fire. Am i doing something wrong? I have imported the ImgFallbackModule as you described. I work on VS 2017 dotnet core Angular 4+ template which uses webpack, if that helps you.

**Comment by VadimDez** [comment]
`[src-fallback]` should be working if you imported the module correctly.
You might need to import this module to the server side rendering module and to see if that fixes your problem.

**Comment by chsakell** [comment]
I import the module in the app.shared.module which is used by both the server side and browser one but no luck.

**Comment by chsakell** [comment]
OK @VadimDez  I found the cause. It was because I was using the directive in a lazy loading module and I had to import it there as well. We may close the ticket.  Very good job with the directive, well done.
